name: ci-test

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

#    services:
#      postgres:
#        image: postgres:14

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '20'
          
     

      - name: ls
        run: ls -R

      - name: Build frontend image
        run: docker image build . -f packages/backend/Dockerfile --tag backstage
        
